security:
  basic:
    enabled: false

management:
  security:
    enabled: false

logging:
  level:
    io:
      pivotal: DEBUG

spring:
  cloud:
    services:
      registrationMethod: direct

greeting:
  displayFortune: true

quoteServiceURL: http://quote-service-dev.cfapps.io/quote